services:
  webapp:
    build: .
    container_name: park-tespit-webapp
    restart: always
    volumes:
      - ./otoparklar.json:/app/otoparklar.json
      - ./system_state.json:/app/system_state.json
    environment:
      - HEADLESS=1
    expose:
      - "3001"
    networks:
      - biryerden-network

networks:
  biryerden-network:
    external: true
